import LegalPage from "@/components/LegalPage";

export const metadata = { title: "Creator Agreement — Gran Boulva" };

export default function CreatorAgreementPage() {
  return (
    <LegalPage
      title="Creator Agreement"
      subtitle="Akò Kreyatè / Creator Agreement"
      effectiveDate="June 4, 2026"
      sections={[
        {
          title: "Who This Agreement Applies To / Kiyès Akò Sa Aplike",
          content: `This Creator Agreement ("Agreement") applies to all Gran Boulva users who have reached Creator Tier 1 or above (Kreyatè Entèmedyè, Kreyatè Verifye, Kreyatè Elit, or Ikòn Kiltirèl). By activating or continuing to hold Creator status, you agree to the terms of this Agreement in addition to the Gran Boulva Terms of Service.

Akò Kreyatè sa a ("Akò") aplike pou tout itilizatè Gran Boulva ki rive nan Nivo Kreyatè 1 oswa pi wo. Lè ou aktive oswa kontinye kenbe estati Kreyatè, ou dakò ak kondisyon Akò sa a anplis Kondisyon Sèvis Gran Boulva yo.`,
        },
        {
          title: "Content Ownership / Pwopriyete Kontni",
          content: `You retain ownership of all original content you create and post on Gran Boulva ("Your Content").

By posting Your Content, you grant Gran Boulva a non-exclusive, royalty-free, worldwide license to display, distribute, and promote Your Content on the platform and in marketing materials. This license ends when you delete the content or close your account, except where Your Content has been shared or interacted with by other users (in which case cached copies may remain briefly).

You are solely responsible for ensuring Your Content does not infringe on third-party copyrights, trademarks, or other rights.

Ou kenbe pwopriyete tout kontni orijinal ou kreye ak poste sou Gran Boulva.`,
        },
        {
          title: "Revenue Sharing / Pataj Revni",
          content: `As a Creator, you are eligible to earn a share of revenue generated by activity on your content, subject to the following:

| Tier | Revenue Share |
|------|--------------|
| Tier 1 — Kreyatè Entèmedyè | 60% |
| Tier 2 — Kreyatè Verifye | 70% |
| Tier 3 — Kreyatè Elit | 80% |
| Tier 4 — Ikòn Kiltirèl | Custom |

Revenue is calculated from coin transactions directly associated with your content (argument boosts, supporter coins). Gran Boulva retains the remaining percentage as a platform fee.

Minimum payout threshold: 1,000 coins (equivalent to $1.00 USD at the rate of $0.001 per coin). Payouts are processed via MonCash (Haiti) or other supported payment methods. Payout rates and methods may change with 30 days' notice.

Gran Boulva reserves the right to withhold or reverse revenue payments if Your Content is found to violate the Terms of Service or this Agreement.`,
        },
        {
          title: "Creator Responsibilities / Responsablite Kreyatè",
          content: [
            "Maintain content quality consistent with Gran Boulva's community standards. | Kenbe kalite kontni ki konsistan ak estanda kominote Gran Boulva a.",
            "Not artificially inflate engagement metrics (self-boosting via multiple accounts, coordinated inauthentic behavior). | Pa gontle metrik angajman atifisyèlman.",
            "Disclose any sponsored or paid content clearly and prominently. | Revele tout kontni sponsorize oswa peye klèman.",
            "Not use Creator tools or revenue access to harass, manipulate, or exploit other users. | Pa itilize zouti Kreyatè oswa aksè revni pou fasite, manipile, oswa eksplwate lòt itilizatè.",
            "Comply with all applicable laws, including tax obligations on revenue earned. | Konfòme ak tout lwa ki aplikab, enkli obligasyon fiskal sou revni ranmase.",
          ],
        },
        {
          title: "Tier Changes and Termination / Chanjman Nivo ak Revokasyon",
          content: `Creator status is dynamic and may be upgraded or downgraded based on your activity score (calculated by Gran Boulva's creator scoring system). You will be notified in-app of any tier change.

Gran Boulva may terminate Creator status and this Agreement at any time if you:
• Violate the Terms of Service or Moderation Policy
• Engage in fraudulent revenue activity
• Become inactive for more than 6 consecutive months

Upon termination, any unpaid revenue above the minimum threshold will be paid out within 30 days. Revenue below the minimum threshold is forfeited.

Estati Kreyatè dinamik e ka monte oswa desann depann de sko aktivite ou.`,
        },
        {
          title: "Taxes / Taks",
          content: `You are solely responsible for reporting and paying any taxes applicable to revenue you earn through Gran Boulva. Gran Boulva does not withhold taxes on creator payouts. We may request tax information (such as a W-9 or equivalent) if required by applicable law.

Ou se sèl responsab pou rapòte ak peye nenpòt taks ki aplikab sou revni ou ranmase atravè Gran Boulva.`,
        },
        {
          title: "Modifications / Modifikasyon",
          content: `Gran Boulva may update this Agreement at any time. We will notify you via in-app notification at least 14 days before changes take effect. Continued use of Creator features after that date constitutes acceptance of the updated Agreement.

Gran Boulva ka mete ajou Akò sa a nenpòt ki lè. Nou pral avèti ou via notifikasyon nan aplikasyon omwen 14 jou anvan chanjman yo antre an vigè.`,
        },
        {
          title: "Contact / Kontak",
          content: `For questions about this Agreement: support@granboulva.com

Gran Boulva — granboulva.com`,
        },
      ]}
    />
  );
}
